import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Grid, Box } from "@mui/material";
import { Appbar } from "./component/Appbar";
import { Titulo } from "./component/Titulo";
import { Slider } from "./component/Slider";
import { Grafico } from "./component/Grafico";
import { Formulario } from "./component/Formulario";
import { Footer } from "./component/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          width: "100%",
          height: "auto",
          padding: "0px",
          backgroundColor: "rgba(0, 0, 0, 0.727)",
        }}
      >
        <Grid container>
          <Grid item xs={12}>
            <Appbar />
          </Grid>

          <Grid
            item
            xs={12}
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              WebkitFlexDirection: "column",
              marginTop: "150px",
              marginBottom: "150px",
            }}
          >
            <Titulo />
          </Grid>

          <Grid
            item
            xs={12}
            sx={{
              bgcolor: "#fff",
              height: "500px",
              position: "relative",
            }}
          >
            <Slider />
          </Grid>

          <Grid item xs={12}>
            <Grafico />
          </Grid>
          <Grid item xs={12}>
            <Formulario />
          </Grid>

          <Grid item xs={12}>
            <Footer />
          </Grid>
        </Grid>
      </Box>
    </>
  );
}
